import 'package:flutter/material.dart';

class CategoryIconResolver {
  static const Map<String, IconData> iconMap = {
    'restaurant': Icons.restaurant,
    'directions_car': Icons.directions_car,
    'home': Icons.home,
    'bolt': Icons.bolt,
    'phone_android': Icons.phone_android,
    'shopping_cart': Icons.shopping_cart,
    'movie': Icons.movie,
    'local_hospital': Icons.local_hospital,
    'money_off': Icons.money_off,
    'savings': Icons.savings,
    'category': Icons.category,
    'fitness_center': Icons.fitness_center,
    'pets': Icons.pets,
    'school': Icons.school,
    'subscriptions': Icons.subscriptions,
    'card_giftcard': Icons.card_giftcard,
    'flight': Icons.flight,
    'health_and_safety': Icons.health_and_safety,
    'child_care': Icons.child_care,
    'water_drop': Icons.water_drop,
    'wifi': Icons.wifi,
    'account_balance': Icons.account_balance,
    'credit_score': Icons.credit_score,
    'work': Icons.work,
    'sports_esports': Icons.sports_esports,
    'fastfood': Icons.fastfood,
    'local_cafe': Icons.local_cafe,
    'local_gas_station': Icons.local_gas_station,
    'train': Icons.train,
    'directions_bus': Icons.directions_bus,
    'two_wheeler': Icons.two_wheeler,
    'local_grocery_store': Icons.local_grocery_store,
    'shopping_bag': Icons.shopping_bag,
    'checkroom': Icons.checkroom,
    'chair': Icons.chair,
    'brush': Icons.brush,
    'construction': Icons.construction,
    'build': Icons.build,
    'music_note': Icons.music_note,
    'sports_basketball': Icons.sports_basketball,
    'pool': Icons.pool,
    'park': Icons.park,
    'menu_book': Icons.menu_book,
    'laptop_mac': Icons.laptop_mac,
    'devices': Icons.devices,
    'pedal_bike': Icons.pedal_bike,
    'volunteer_activism': Icons.volunteer_activism,
    'celebration': Icons.celebration,
    'spa': Icons.spa,
    'family_restroom': Icons.family_restroom,
    'cottage': Icons.cottage,
    'attach_money': Icons.attach_money,
    'account_tree': Icons.account_tree,
  };

  static const Map<String, List<String>> keywordMap = {
    'restaurant': ['food', 'dining', 'eating', 'meal', 'restaurant'],
    'directions_car': ['transport', 'car', 'vehicle', 'driving', 'auto'],
    'home': ['housing', 'rent', 'home', 'house', 'mortgage'],
    'bolt': ['utility', 'electricity', 'power', 'energy', 'flash'],
    'phone_android': ['phone', 'mobile', 'cell', 'communication'],
    'shopping_cart': ['shopping', 'groceries', 'buy', 'cart', 'market'],
    'movie': ['entertainment', 'movie', 'film', 'cinema', 'watch'],
    'local_hospital': ['health', 'medical', 'hospital', 'doctor', 'clinic'],
    'money_off': ['debt', 'loan', 'borrow', 'owe', 'off'],
    'savings': ['savings', 'bank', 'deposit', 'piggy', 'invest'],
    'category': ['other', 'misc', 'shapes', 'general'],
    'fitness_center': ['gym', 'fitness', 'workout', 'exercise', 'weights'],
    'pets': ['pets', 'animals', 'dog', 'cat', 'vet'],
    'school': ['education', 'school', 'learning', 'tuition', 'study'],
    'subscriptions': ['subscription', 'recurring', 'netflix', 'media', 'bill'],
    'card_giftcard': ['gifts', 'present', 'card', 'holiday', 'birthday'],
    'flight': ['travel', 'flight', 'airplane', 'vacation', 'trip'],
    'health_and_safety': ['insurance', 'safety', 'shield', 'secure', 'health'],
    'child_care': ['childcare', 'kids', 'baby', 'children', 'daycare'],
    'water_drop': ['water', 'bill', 'utility', 'drop', 'liquid'],
    'wifi': ['internet', 'wifi', 'web', 'connection', 'data'],
    'account_balance': ['bank', 'government', 'tax', 'official', 'institution'],
    'credit_score': ['credit', 'score', 'rating', 'loan', 'finance'],
    'work': ['work', 'job', 'salary', 'income', 'business'],
    'sports_esports': ['gaming', 'games', 'play', 'console', 'controller'],
    'fastfood': ['fastfood', 'burger', 'junk', 'snack', 'eating'],
    'local_cafe': ['coffee', 'cafe', 'tea', 'drink', 'mug'],
    'local_gas_station': ['gas', 'fuel', 'petrol', 'pump', 'car'],
    'train': ['train', 'subway', 'metro', 'transit', 'rail'],
    'directions_bus': ['bus', 'transit', 'public', 'transport', 'coach'],
    'two_wheeler': ['bike', 'motorcycle', 'scooter', 'cycle', 'ride'],
    'local_grocery_store': ['grocery', 'store', 'shop', 'food', 'market'],
    'shopping_bag': ['clothes', 'apparel', 'shopping', 'bag', 'retail'],
    'checkroom': ['clothes', 'fashion', 'hanger', 'closet', 'apparel'],
    'chair': ['furniture', 'home', 'decor', 'seat', 'living'],
    'brush': ['art', 'paint', 'hobby', 'craft', 'creative'],
    'construction': ['repair', 'construction', 'build', 'tools', 'fix'],
    'build': ['wrench', 'tools', 'repair', 'fix', 'mechanic'],
    'music_note': ['music', 'song', 'audio', 'listen', 'concert'],
    'sports_basketball': ['sports', 'basketball', 'game', 'play', 'athletics'],
    'pool': ['swim', 'pool', 'water', 'leisure', 'recreation'],
    'park': ['nature', 'park', 'tree', 'outdoor', 'recreation'],
    'menu_book': ['book', 'reading', 'study', 'learn', 'menu'],
    'laptop_mac': ['electronics', 'computer', 'laptop', 'tech', 'device'],
    'devices': ['devices', 'electronics', 'tech', 'gadget', 'phone'],
    'pedal_bike': ['bicycle', 'bike', 'cycle', 'fitness', 'ride'],
    'volunteer_activism': ['charity', 'donation', 'heart', 'give', 'volunteer'],
    'celebration': ['party', 'event', 'celebration', 'fun', 'festivity'],
    'spa': ['spa', 'massage', 'relax', 'wellness', 'beauty'],
    'family_restroom': ['family', 'relatives', 'parents', 'dependants', 'restroom'],
    'cottage': ['holiday home', 'cottage', 'cabin', 'vacation', 'retreat'],
    'attach_money': ['cash', 'money', 'dollar', 'currency', 'bill'],
    'account_tree': ['project', 'tree', 'structure', 'organize', 'branch'],
  };

  /// Resolves a string icon name (e.g., 'phone_android') to its IconData.
  /// If the name is unknown, returns a fallback generic category icon.
  static IconData resolve(String iconName) {
    return iconMap[iconName] ?? Icons.category;
  }
}
